export const styles = {

  webInfo: {
    position: 'relative',
    float: 'left',
    width: '80vw',
    height: 'calc(85vh - 30vh)',
    backgroundColor: 'rgba(100, 100, 100, 0.1)',
    marginLeft: '10vw',
    marginRight: '10vw',
    marginTop: '15vh',
    marginBottom: '15vh',
    zIndex: 10,
  },
  webHeader: {
    position: 'relative',
    float: 'left',
    width: '100%',
    textAlign: 'center',
    fontSize: 40,
    marginTop: 20,
    fontFamily: 'Nothing You Could Do, cursive'
  },
  webText: {
    position: 'relative',
    float: 'left',
    width: '80%',
    marginLeft: '10%',
    marginRight: '10%',
    marginTop: 20,
    fontSize: 15,
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: 'Muli, sans-serif',
    color: 'rgb(52, 52, 52)',
  },
  webList: {
    position: 'relative',
    float: 'left',
    width: '70%',
    marginLeft: '15%',
    marginRight: '15%',
    fontSize: 12,
    marginTop: 3,
    marginBottom: 3,
    textAlign: 'center',
    fontFamily: 'Muli, sans-serif',
    color: 'rgb(52, 52, 52)',
  },
  iconOne: {
    position: 'absolute',
    top: 20,
    left: '3%',
    width: 200,
    zIndex: 3,
    transform: 'rotate(20deg)',
  },
  iconTwo: {
    position: 'absolute',
    bottom: 70,
    right: '5%',
    width: 250,
    zIndex: 3,
  }
};
