export const styles = {
  main: {
    position: 'relative',
    float: 'left',
    width: '80%',
    marginLeft: '10%',
    marginRight: '10%',
    marginTop: '5%',
    marginBottom: '5%',
    backgroundColor: 'rgba(251, 204, 209, 0.25)',
  },
  container: {
    position: 'relative',
    float: 'left',
    width: '90%',
    height: '90%',
    margin: '5%',
    overflowX: 'hidden',
  },
  title: {
    position: 'relative',
    float: 'left',
    textAlign: 'center',
    width: '95%',
    padding: '2.5%',
    fontFamily: 'Nothing You Could Do, cursive',
    fontSize: 40,
  },
  text: {
    position: 'relative',
    float: 'left',
    textAlign: 'center',
    width: '100%',
    marginTop: 'calc(1% + 5px)',
    marginBottom: 'calc(1% + 5px)',
    color: 'rgba(0, 0, 0, 0.65)',
    fontSize: 'calc(13px + 0.35vw)',
  },
};
