export const styles = {
  main: {
    position: 'relative',
    float: 'left',
    width: '100%',
    backgroundColor: 'rgba(251, 204, 209, 0.25)',
  },
  mapContainer: {
    position: 'relative',
    width: '100vw',
    bottom: 0,
    left: -23,
    height: '50vh',
    zIndex: 0,
    overflow: 'hidden',
  },
  infoContainerMobile: {
    position: 'relative',
    width: '90vw',
    marginLeft:'5vw',
    height: 120,
    top: 0,
    left: 0,
    zIndex: 0,
  },
  mobileTitle: {
    marginTop: 50,
    position: 'relative',
    float: 'left',
    width: '100%',
    color: 'rgb(100,100,100)',
    fontSize: 30,
    zIndex: 2,
    textAlign: 'center',
  },
  infoHolderMobile: {
    position: 'relative',
    marginTop: 50,
    padding: 20,
    float: 'left',
    width: '80%',
    marginLeft: 'calc(10% - 10px)',
    marginRight: 'calc(10% - 10px)',
    zIndex: 2,
  },
  infoContainer: {
    position: 'absolute',
    width: '95vw',
    paddingLeft:'5vw',
    height: 'calc(100vh - 55vh - 140px)',
    backgroundColor: 'rgb(255, 255, 255)',
    bottom: 0,
    left: 0,
    zIndex: 0,
  },
  infoHolder: {
    position: 'relative',
    marginTop: 20,
    float: 'left',
    width: '23%',
    marginLeft: '5%',
    marginRight: '5%',
    zIndex: 2,
  },
  text: {
    position: 'relative',
    width: '100%',
    marginBottom: 10,
    float: 'left',
    color: 'rgb(100,100,100)',
    zIndex: 2,
    fontSize: 20,
    textAlign: 'center',
    paddingBottom: 10,
    borderBottom: '1px solid rgb(150, 150, 150)'
  },
  data: {
    position: 'relative',
    width: '100%',
    float: 'left',
    color: 'rgb(150,150,150)',
    fontSize: 15,
    marginBottom: 5,
    zIndex: 2,
    textAlign: 'center',
  },
  dataLeft: {
    position: 'relative',
    width: '20%',
    marginLeft: '25%',
    float: 'left',
    color: 'rgb(150,150,150)',
    fontSize: 15,
    zIndex: 2,
    textAlign: 'left',
  },
  dataRight: {
    position: 'relative',
    width: '40%',
    marginLeft: '10%',
    float: 'left',
    color: 'rgb(150,150,150)',
    fontSize: 15,
    zIndex: 2,
    textAlign: 'left',
  },
};
