export const styles = {
  main: {
    position: 'absolute',
    width: '80%',
    height: '100%',
    overflowY: 'hidden',
  },
  container: {
    position: 'relative',
    float: 'left',
    width: 'calc((70vw / 3))',
    marginLeft: 20,
    marginRight: 20,
    marginTop: 10,
    marginBottom: 10,
  },
  title: {
    position: 'relative',
    float: 'left',
    width: '100%',
    fontSize: 18,
    marginLeft: 5,
    marginTop: 10,
    marginBottom: 10,
  },
  subtext: {
    position: 'relative',
    float: 'left',
    width: 'calc(100% - 10px)',
    marginTop: -30,
    marginBottom: 35,
    marginLeft: 3,
    marginRight: 5,
    fontSize: 9,
    color: 'rgba(100, 100, 100, 1)',
  },
  subTitleMain: {
    position: 'relative',
    float: 'left',
    width: 'calc(100% - 10px)',
    marginBottom: 5,
    marginLeft: 3,
    marginRight: 5,
    fontSize: 9,
    color: 'rgba(100, 100, 100, 1)',
  },
  subTitle: {
    position: 'relative',
    float: 'left',
    width: 'calc(80% - 10px)',
    marginBottom: 5,
    marginLeft: 3,
    marginRight: 5,
    fontSize: 8,
    color: 'rgba(100, 100, 100, 1)',
  },
  itemName: {
    position: 'relative',
    float: 'left',
    width: 'calc(55% - 10px)',
    fontSize: 11,
    marginTop: 6,
    marginLeft: 5,
    marginRight: 5,
  },
  itemPrice: {
    position: 'relative',
    float: 'right',
    textAlign: 'right',
    width: 'calc(35% - 10px)',
    fontSize: 11,
    marginTop: 6,
    marginLeft: 5,
    marginRight: 5,
    color: 'rgba(100, 100, 100, 1)',
  },
  footer: {
    width: '50%',
    padding: 30,
    float: 'right',
    position: 'static',
    bottom: 0
  },

  test: {
    position: 'relative',
    float: 'left',
    overflowY: 'scroll',
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(1, 1, 1, 0.1)',
  }


};
