export const styles = {
  main: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100vw',
    maxWidth: '100%',
    height: '85vh',
  },
  mapContainer: {
    position: 'absolute',
    width: '100%',
    height: '45vh',
    top: 0,
    right: 0,
    zIndex: 0,
  },
  infoContainer: {
    position: 'absolute',
    width: '95vw',
    paddingLeft:'5vw',
    height: 'calc(100vh - 50vh - 140px)',
    backgroundColor: 'rgb(255, 255, 255)',
    bottom: 0,
    left: 0,
    zIndex: 0,
  },
  infoContainerMobile: {
    position: 'absolute',
    width: '90vw',
    marginLeft:'5vw',
    height: 'calc(85vw)',
    top: 0,
    left: 0,
    zIndex: 0,
  },
  mobileTitle: {
    marginTop: 50,
    position: 'relative',
    float: 'left',
    width: '100%',
    color: 'rgb(100,100,100)',
    fontSize: 30,
    zIndex: 2,
    textAlign: 'center',
  },
  subTitleMobile: {
    position: 'relative',
    float: 'left',
    width: '100%',
    color: 'rgb(100,100,100)',
    fontSize: 15,
    zIndex: 2,
    textAlign: 'center',
  },
  infoHolder: {
    position: 'relative',
    marginTop: 20,
    float: 'left',
    width: '23%',
    marginLeft: '5%',
    marginRight: '5%',
    zIndex: 2,
  },
  infoHolderMobile: {
    position: 'relative',
    marginTop: 40,
    float: 'left',
    width: '60%',
    marginLeft: '20%',
    marginRight: '20%',
    zIndex: 2,
  },
  text: {
    position: 'relative',
    width: '100%',
    marginBottom: 10,
    float: 'left',
    color: 'rgb(100,100,100)',
    zIndex: 2,
    fontSize: 20,
    textAlign: 'center',
    paddingBottom: 10,
    borderBottom: '1px solid rgb(150, 150, 150)'
  },
  data: {
    position: 'relative',
    width: '100%',
    float: 'left',
    color: 'rgb(150,150,150)',
    fontSize: 15,
    marginBottom: 5,
    zIndex: 2,
    textAlign: 'center',
  },
  dataLeft: {
    position: 'relative',
    width: '20%',
    float: 'left',
    color: 'rgb(150,150,150)',
    fontSize: 15,
    zIndex: 2,
    textAlign: 'right',
  },
  dataRight: {
    position: 'relative',
    width: '70%',
    marginLeft: '10%',
    float: 'left',
    color: 'rgb(150,150,150)',
    fontSize: 15,
    zIndex: 2,
    textAlign: 'right',
  }
};
